"""empty message

Revision ID: 4255cd369c61
Revises: aa164b81431b
Create Date: 2022-06-13 00:57:40.735650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4255cd369c61'
down_revision = 'aa164b81431b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poem', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('poem', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poem', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('poem', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
